apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-{{ .Release.Name }}
  namespace: {{  .Release.Namespace }}
spec:
  ports:
  - name: {{ .Values.service.name }}-{{ .Release.Name }}
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.labels.app }}
  type: ClusterIP